
INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (1, 'Борщ с пампушками', 450.00, 'https://laplacinte.md/public/product_images/99/999/a48fb0b681270dfbb96a277c3dec604a.webp',
        'Классический украинский борщ с говядиной, подается со свежими пампушками и сметаной', 350),
       (1, 'Куриные котлеты по-киевски', 680.00, 'https://bahetle-sib.ru/storage/goods/72539.jpg',
        'Нежные куриные котлеты с масляно-зеленым соусом внутри, подаются с картофельным пюре', 280),
       (1, 'Салат "Оливье', 320.00, 'https://images.gastronom.ru/sI2Z_hS9qg62A_PIvSNDCqpsBvIKqOpRSYTVehfE9KA/pr:recipe-cover-image/g:ce/rs:auto:0:0:0/L2Ntcy9hbGwtaW1hZ2VzL2QxOTg4MmNjLTU1YjAtNDQ5ZS05Nzc3LTkzNDUzNGYxMzZkMi5qcGc.webp',
        'Традиционный новогодний салат с колбасой, овощами и майонезом', 200),
       (1, 'Гречневая каша с грибами', 390.00, 'https://images.gastronom.ru/e0WGo29wkuMoVzzDgTY79c4kFmzGKGhG6wVtZTyx104/pr:recipe-preview-image/g:ce/rs:auto:0:0:0/L2Ntcy9hbGwtaW1hZ2VzLzMzZTk0ZWQ1LWQyZjUtNDk3YS05MzJlLTcyYTQwOWExMDYxNi5qcGc.webp',
        'Ароматная гречка с лесными грибами и луком', 250),
       (1, 'Блины с красной икрой', 850.00, 'https://images.gastronom.ru/1AI9fdKy9X-5Ud69Zry6kp7-QZdDXOvgg6eq0VM_eyE/pr:recipe-cover-image/g:ce/rs:auto:0:0:0/L2Ntcy9hbGwtaW1hZ2VzLzM2OWM3MmY1LWQ1NjctNGIwMi1hMjJjLTdlZGE2NGJjMDVjZi5qcGc.webp',
        'Тонкие блины с красной икрой и сметаной', 180),
       (1, 'Уха царская', 550.00, 'https://i.ytimg.com/vi/CAi3VhHRJdA/maxresdefault.jpg', 'Наваристая уха из трех видов рыбы с овощами',
        300),
       (1, 'Гуляш из говядины', 620.00, 'https://www.chefmarket.ru/blog/wp-content/uploads/2018/11/beef-ulyash-e1542885200374.jpg',
        'Густой мясной гуляш с подливкой, подается с гречневой кашей', 320),
       (1, 'Сырники со сметаной', 290.00, 'https://madamcho.ru/image/catalog/deserty/11.jpeg',
        'Нежные творожные сырники с ванильным соусом', 220),
       (1, 'Винегрет', 270.00, 'https://fort.crimea.com/catering/uploads/fotos/a89f02c9-65c2-11e9-9c6d-54a05051519a_1.jpg',
        'Овощной салат со свеклой, картофелем и солеными огурцами', 200),
       (1, 'Медовик', 350.00, 'https://cdnn21.img.ria.ru/images/07e8/09/10/1972971537_0:159:3076:1889_1920x1080_80_0_0_bf8c3059c02760346886670321765108.jpg', 'Классический медовый торт со сметанным кремом',
        150);

INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (2, 'Классический бургер', 590.00, 'https://www.chefmarket.ru/blog/wp-content/uploads/2020/11/hamburger-2000x1200.jpg',
        'Говяжья котлета, сыр чеддер, салат, помидор и фирменный соус', 300),
       (2, 'Картофель фри', 220.00, 'https://www.chefmarket.ru/blog/wp-content/uploads/2018/05/3_1524290681_3d8bd.jpg', 'Хрустящий картофель с паприкой и солью',
        150),
       (2, 'Куриные крылышки Buffalo', 480.00, 'https://static.pizzasushiwok.ru/images/menu_new/657-1300.jpg',
        'Хрустящие куриные крылышки в остром соусе Buffalo', 250),
       (2, 'Молочный коктейль ванильный', 320.00, 'https://hinkali-tancevali.ru/wp-content/uploads/2019/04/%D0%9C%D0%BE%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BE%D0%BA%D1%82%D0%B5%D0%B9%D0%BB%D1%8C-%D0%B2%D0%B0%D0%BD%D0%B8%D0%BB%D1%8C-min-scaled.jpg',
        'Густой молочный коктейль с ванильным мороженым', 400),
       (2, 'Чизкейк Нью-Йорк', 420.00, 'https://la-torta.ua/content/uploads/images/12-cake.jpg',
        'Классический чизкейк с ягодным соусом', 180),
       (2, 'Сэндвич с пастрами', 540.00, 'https://image.danilovskymarket.ru/w:656/h:440/aHR0cHM6Ly9iYWNrLmRhbmlsb3Zza3ltYXJrZXQucnUvZmlsZXMvMTIyMGI3ZjktNDk0MS00NjNkLTk0NTYtZGI2ZWQ3NWM5ZDk5MzMlRDElODkuanBn',
        'Рубленое мясо пастрами с горчицей на ржаном хлебе', 280),
       (2, 'Яблочный пирог', 290.00, 'https://tgifridays.ru/wa-data/public/shop/products/51/02/30251/images/10118437/10118437.900x616.jpg',
        'Домашний яблочный пирог с корицей и ванильным мороженым', 200),
       (2, 'Омлет с беконом', 380.00, 'https://www.chefmarket.ru/blog/wp-content/uploads/2022/02/omelet-with-bacon-1-e1645288405543.jpg',
        'Пушистый омлет с хрустящим беконом и зеленью', 250),
       (2, 'Салат Цезарь', 450.00, 'https://canapeclub.ru/image/cache/catalog/product/30-10-2019/cezar-818x818.jpg',
        'Классический салат с курицей, крутонами и соусом Цезарь', 220),
       (2, 'Хот-дог чикагский', 370.00, 'https://vostochka56.ru/sites/default/files/6u5a6353.jpg',
        'Хот-дог с разнообразными овощными добавками и горчицей', 220);

INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (3, 'Карбонара', 620.00, 'https://cdn.bellinigroup.ru/upload/202006/5ef98e4e8d9f0_1080x1080_fit.png',
        'Спагетти с беконом, сливочным соусом и яичным желтком', 300),
       (3, 'Болоньезе', 580.00, 'https://obed-gotov.ru/wp-content/uploads/2021/03/133dcc5909.jpg',
        'Спагетти с мясным соусом из говядины и томатов', 320),
       (3, 'Лазанья классическая', 750.00, 'https://www.chefmarket.ru/blog/wp-content/uploads/2021/01/a-piece-of-chicken--2000x1200.jpg',
        'Слоеная паста с мясной начинкой и сыром бешамель', 350),
       (3, 'Феттучини Альфредо', 670.00, 'https://djama.kz/wp-content/uploads/2024/02/pasta-fetuchini-s-sousom-alfredo.jpg',
        'Ленточная паста с сливочным соусом и пармезаном', 280),
       (3, 'Равиоли с рикоттой', 690.00, 'https://www.ermolino-produkty.ru/picts/products/ravioli-rikotta-shpinat.jpg',
        'Итальянские пельмени с начинкой из рикотты и шпината', 250),
       (3, 'Пенне Арраббиата', 540.00, 'https://api.syrovarnya.com/sites/default/files/styles/image_690x690/public/catalog/100012162.jpg?itok=BzQjW0aS',
        'Перьевые макароны с острым томатным соусом', 270),
       (3, 'Ризотто с грибами', 720.00, 'https://nonna.com.ua/image/catalog/rolly/0f881414-728d-4251-af84-f6e7fb8448e7.jpeg',
        'Кремовое ризотто с лесными грибами и пармезаном', 300),
       (3, 'Гноччи с сыром', 650.00, 'https://cdn.bellinigroup.ru/upload/202207/62c5c4fb4e0e6_1080x1080_fit_70_1c1c1e.png', 'Картофельные клецки с сырным соусом',
        280),
       (3, 'Тирамису', 480.00, 'https://cafe-fresco.ru/wp-content/uploads/2020/05/fresco_delivery1167_1.jpg',
        'Классический итальянский десерт с кофе и маскарпоне', 200),
       (3, 'Капрезе', 520.00, 'https://tearoom1.ru/wp-content/uploads/2020/01/%D0%9A%D0%B0%D0%BF%D1%80%D0%B5%D0%B7%D0%B5_1600%D1%851200.jpg', 'Салат с моцареллой, помидорами и базиликом',
        220);

INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (4, 'Ролл Филадельфия', 890.00, 'https://sushiwok.ru/img/d8f116c4ad734759f875095afcfa30c6',
        'Лосось, сливочный сыр, огурец, рис, нори', 240),
       (4, 'Ролл Калифорния', 780.00, 'https://sushiwok.kg/img/02e00e7fc87d69d2d6d27f0ac39220df',
        'Крабовая смесь, авокадо, огурец, икра тобико', 220),
       (4, 'Сет "Самурай"', 2200.00, 'https://ym1.by/wp-content/uploads/2022/02/19.-32-samuraya.jpg',
        'Ассорти из 24 кусочков: роллы с лососем, тунцом и угрем', 600),
       (4, 'Суши с тунцом', 450.00, 'https://kaif.md/wp-content/uploads/2022/06/sushi-tunec.jpg', '2 шт. суши с филе свежего тунца', 80),
       (4, 'Сашими из лосося', 920.00, 'https://i.ytimg.com/vi/b4tpHMc6nNI/maxresdefault.jpg', '8 тонких ломтиков свежего лосося',
        160),
       (4, 'Супу с мисо', 320.00, 'https://akitamarket.ru/wp-content/uploads/2019/11/miso.jpg',
        'Традиционный японский суп с тофу и водорослями', 250),
       (4, 'Темпура с креветками', 680.00, 'https://sushi-luki.ru/assets/images/products/129/tempura-s-krevetkami-i-syirom-krevetka-tigr-tomat-slivochnyij-syir-klyar-suxari-panirovochnyie-8-sht.jpg',
        'Хрустящие креветки в кляре с соусом темпура', 200),
       (4, 'Рамен с курицей', 750.00, 'https://static.1000.menu/img/content-v2/8b/a1/73703/sup-ramen-s-kuricei_1680674711_3_max.jpg', 'Японский суп с лапшой, курицей и яйцом',
        400),
       (4, 'Гунканы с икрой', 580.00, 'https://bluefin.moscow/upload/resize_cache/iblock/dce/b2k4uh85mih8nkeeddapgh0204xb0d9b/1000_1000_0/c8a49d86_42ad_4447_981e_e260f606be8b.jpg',
        '4 шт. рисовых корабликов с икрой летучей рыбы', 120),
       (4, 'Мохито Моти', 290.00, 'https://eda.ru/images/RecipeOpenGraph/1200x630/pirozhnoe-moti-s-zelenym-chaem_93627_ogimage.jpg',
        'Десерт из рисового теста с начинкой из зеленого чая', 100);

INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (5, 'Плов узбекский', 850.00, 'https://images.gastronom.ru/vS3eDA6DMddFCsm2Bv0P1yuw1SOCkmLYhYTJo53SwZo/pr:recipe-cover-image/g:ce/rs:auto:0:0:0/L2Ntcy9hbGwtaW1hZ2VzLzU2OTU3OTRkLTZiYmEtNGI1YS05ZWM1LWViZDVkZWE4MGEyNy5qcGc.webp',
        'Традиционный плов с бараниной, морковью и рисом', 350),
       (5, 'Шашлык из баранины', 920.00, 'https://rutxt.ru/files/15888/final/02658cf8a4.JPG',
        'Нежное мясо молодого барашка на углях', 300),
       (5, 'Манты', 680.00, 'https://media-cdn.tripadvisor.com/media/photo-s/12/a2/68/25/caption.jpg', '6 шт. крупных мантов с мясной начинкой', 400),
       (5, 'Лагман', 720.00, 'https://media-cdn.tripadvisor.com/media/photo-s/10/e2/d1/18/lagman-from-babadjanov.jpg', 'Густой суп с лапшой, мясом и овощами', 450),
       (5, 'Самса с мясом', 180.00, 'https://navat.kg/dostavka/files/products/samsa-s-myasom.800x600w.jpg', '3 шт. слоеных пирожков с мясной начинкой',
        200),
       (5, 'Чучвара', 490.00, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwFKNcnN-ENP-qE04GrL2V_Yl-DwNMdsp_Iw&s', 'Узбекские пельмени в ароматном бульоне',
        300),
       (5, 'Долма', 640.00, 'https://eda.yandex.ru/images/3816972/d5b5b6d74748cb33a50f6cf9c5acbd8e-684x520.jpeg', 'Виноградные листья с мясо-рисовой начинкой', 250),
       (5, 'Шорпо', 580.00, 'https://navat.kg/dostavka/files/products/shorpo.800x600w.jpg', 'Наваристый суп с бараниной и овощами', 400),
       (5, 'Нарын', 750.00, 'https://navat.kg/dostavka/files/products/naryn.800x600w.jpg', 'Холодная закуска из конины с лапшой', 300),
       (5, 'Халва', 220.00, 'https://ss.sport-express.ru/userfiles/materials/197/1976588/volga.jpg', 'Восточная сладость из кунжута и орехов', 150);

-- Блюда для ресторана "Пицца Экспресс" (restaurants_id = 6)
INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (6, 'Пицца Маргарита', 690.00, 'https://example.com/dishes/margherita.jpg',
        'Классическая пицца с томатным соусом, моцареллой и базиликом', 450),
       (6, 'Пицца Пепперони', 850.00, 'https://example.com/dishes/pepperoni.jpg',
        'Острая пицца с колбасой пепперони и сыром', 480),
       (6, 'Пицца Четыре сыра', 920.00, 'https://example.com/dishes/4cheese.jpg',
        'Смесь моцареллы, горгонзолы, пармезана и эмменталя', 470),
       (6, 'Пицца Гавайская', 780.00, 'https://example.com/dishes/hawaiian.jpg',
        'С ветчиной, ананасами и сыром моцарелла', 460),
       (6, 'Пицца Карбонара', 890.00, 'https://example.com/dishes/carbonara_pizza.jpg',
        'С беконом, сливочным соусом и яйцом', 490),
       (6, 'Пицца Диабло', 820.00, 'https://example.com/dishes/diablo.jpg',
        'Острая пицца с салями, перцем чили и халапеньо', 480),
       (6, 'Кальцоне', 650.00, 'https://example.com/dishes/calzone.jpg', 'Закрытая пицца с ветчиной, грибами и сыром',
        400),
       (6, 'Салат с моцареллой', 540.00, 'https://example.com/dishes/mozzarella_salad.jpg',
        'Свежие томаты, моцарелла и базилик', 250),
       (6, 'Чесночные палочки', 320.00, 'https://example.com/dishes/garlic_bread.jpg',
        'Хрустящее тесто с чесночным соусом', 200),
       (6, 'Тирамису', 480.00, 'https://example.com/dishes/tiramisu_pizza.jpg', 'Классический итальянский десерт', 180);

-- Блюда для ресторана "Стейкхаус Прайм" (restaurants_id = 7)
INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (7, 'Рибай стейк', 2500.00, 'https://example.com/dishes/ribeye.jpg',
        'Премиальный кусок говядины с мраморной текстурой', 400),
       (7, 'Филе-миньон', 2800.00, 'https://example.com/dishes/filet.jpg', 'Нежнейшая вырезка высшей категории', 350),
       (7, 'Томагавк стейк', 3200.00, 'https://example.com/dishes/tomahawk.jpg',
        'Большой стейк на кости с насыщенным вкусом', 600),
       (7, 'Бургер из мраморной говядины', 950.00, 'https://example.com/dishes/beef_burger.jpg',
        'Бургер из премиальной говядины с трюфельным соусом', 350),
       (7, 'Запеченый картофель', 420.00, 'https://example.com/dishes/baked_potato.jpg',
        'Картофель с сыром чеддер и беконом', 250),
       (7, 'Спаржа на гриле', 580.00, 'https://example.com/dishes/asparagus.jpg',
        'Свежая спаржа с оливковым маслом и лимоном', 200),
       (7, 'Фуа-гра', 1500.00, 'https://example.com/dishes/foie_gras.jpg', 'Утиная печень с ягодным соусом', 150),
       (7, 'Креветки гриль', 1200.00, 'https://example.com/dishes/shrimp.jpg',
        'Крупные тигровые креветки с чесночным соусом', 300),
       (7, 'Салат "Цезарь" с креветками', 850.00, 'https://example.com/dishes/caesar_shrimp.jpg',
        'Классический Цезарь с тигровыми креветками', 280),
       (7, 'Чизкейк Нью-Йорк', 650.00, 'https://example.com/dishes/ny_cheesecake.jpg',
        'Классический десерт с ягодным соусом', 200);

-- Блюда для ресторана "Аппетит" (restaurants_id = 8)
INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (8, 'Жаркое по-домашнему', 620.00, 'https://example.com/dishes/zharkoe.jpg',
        'Говядина, тушеная с картофелем и овощами', 400),
       (8, 'Куриная грудка в сливочном соусе', 540.00, 'https://example.com/dishes/chicken_cream.jpg',
        'Нежная куриная грудка под сливочно-грибным соусом', 300),
       (8, 'Греческий салат', 450.00, 'https://example.com/dishes/greek_salad.jpg',
        'Свежие овощи, фета, оливки и оливковое масло', 250),
       (8, 'Суп-пюре из шампиньонов', 380.00, 'https://example.com/dishes/mushroom_soup.jpg',
        'Нежный крем-суп с грибами и сливками', 300),
       (8, 'Картофельные драники', 290.00, 'https://example.com/dishes/draniki.jpg',
        'Хрустящие картофельные оладьи со сметаной', 200),
       (8, 'Голубцы', 480.00, 'https://example.com/dishes/golubtsy.jpg', 'Капустные листья с мясо-рисовой начинкой',
        300),
       (8, 'Сырная тарелка', 750.00, 'https://example.com/dishes/cheese_plate.jpg',
        'Ассорти из сыров с орехами и медом', 250),
       (8, 'Шарлотка с яблоками', 320.00, 'https://example.com/dishes/charlotte.jpg',
        'Домашний яблочный пирог с ванильным соусом', 200),
       (8, 'Винегрет', 270.00, 'https://example.com/dishes/vinegret2.jpg',
        'Овощной салат со свеклой и солеными огурцами', 220),
       (8, 'Компот из сухофруктов', 180.00, 'https://example.com/dishes/compote.jpg',
        'Освежающий напиток из сушеных фруктов', 500);

-- Блюда для ресторана "Дом перемен" (restaurants_id = 9)
INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (9, 'Утка по-пекински', 1800.00, 'https://example.com/dishes/peking_duck.jpg',
        'Хрустящая утка с тонкими блинчиками и соусом', 500),
       (9, 'Кисло-сладкая свинина', 850.00, 'https://example.com/dishes/sweet_sour_pork.jpg',
        'Хрустящие кусочки свинины в кисло-сладком соусе', 350),
       (9, 'Курица генерала Цо', 780.00, 'https://example.com/dishes/general_tsos.jpg',
        'Острая курица в хрустящей панировке', 320),
       (9, 'Вонтоны жареные', 420.00, 'https://example.com/dishes/wonton.jpg',
        '6 шт. хрустящих пельменей с мясной начинкой', 200),
       (9, 'Суп том ям', 650.00, 'https://example.com/dishes/tom_yum.jpg',
        'Острый тайский суп с креветками и кокосовым молоком', 350),
       (9, 'Лапша удон с овощами', 580.00, 'https://example.com/dishes/udon.jpg',
        'Толстая лапша с овощами в устричном соусе', 400),
       (9, 'Баклажаны в соусе чили', 490.00, 'https://example.com/dishes/eggplant.jpg',
        'Обжаренные баклажаны с острым соусом', 300),
       (9, 'Жареный рис с морепродуктами', 720.00, 'https://example.com/dishes/fried_rice.jpg',
        'Рис с креветками, кальмарами и овощами', 450),
       (9, 'Спринг-роллы', 380.00, 'https://example.com/dishes/spring_rolls.jpg', '4 шт. хрустящих роллов с овощами',
        200),
       (9, 'Мороженое с жареным бананом', 450.00, 'https://example.com/dishes/fried_banana.jpg',
        'Десерт с карамелизированным бананом и ванильным мороженым', 250);

-- Блюда для ресторана "Бистро" (restaurants_id = 10)
INSERT INTO dishes (restaurants_id, name, price, photo_url, description, weight)
VALUES (10, 'Круассан с ветчиной и сыром', 320.00, 'https://example.com/dishes/croissant.jpg',
        'Свежий круассан с начинкой из ветчины и сыра', 150),
       (10, 'Салат Нисуаз', 480.00, 'https://example.com/dishes/nicoise.jpg',
        'Салат с тунцом, яйцом, стручковой фасолью и овощами', 280),
       (10, 'Луковый суп', 350.00, 'https://example.com/dishes/onion_soup.jpg',
        'Классический французский суп с сырной корочкой', 300),
       (10, 'Киш Лорен', 420.00, 'https://example.com/dishes/quiche.jpg', 'Открытый пирог с ветчиной, сыром и сливками',
        250),
       (10, 'Багет с паштетом', 290.00, 'https://example.com/dishes/baguette.jpg',
        'Свежий багет с домашним паштетом и корнишонами', 200),
       (10, 'Тар-тар из говядины', 680.00, 'https://example.com/dishes/tartare.jpg',
        'Сырая говяжья вырезка с яичным желтком и каперсами', 250),
       (10, 'Рататуй', 540.00, 'https://example.com/dishes/ratatouille.jpg',
        'Овощное рагу из баклажанов, кабачков и перцев', 300),
       (10, 'Фондю сырное', 950.00, 'https://example.com/dishes/fondue.jpg',
        'Смесь сыров с белым вином, подается с хлебом', 400),
       (10, 'Профитроли', 380.00, 'https://example.com/dishes/profiteroles.jpg',
        'Заварные пирожные с шоколадным соусом', 200),
       (10, 'Кафе глассе', 220.00, 'https://example.com/dishes/coffee.jpg', 'Холодный кофе с мороженым', 300);